version: "3"
services:
  mydb:
    image: mysql
    environment:
      MYSQL_DATABASE: RMDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mydb