spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mydb:3306/RMDB?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: root
mybatis:
  type-aliases-package: com.cya.rm.myProject.vo